config/routes.rb
Rails.application.routes.draw do
  resources :bulk_accounts, only: %i[ new create ]
  namespace :bulk_accounts do
    resource :group, only: :create
  end
  root to: redirect("/bulk_accounts/new")
end

app/models/account.rb
class Account < ApplicationRecord
  validates :name, :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bulk_accounts/groups_controller.rb
class BulkAccounts::GroupsController < ApplicationController
  def create
  end
end

app/controllers/bulk_accounts_controller.rb
class BulkAccountsController < ApplicationController
  def new
    @accounts = 1.times.map{ Account.new }
  end

  def create
    is_success = false
    @accounts = accounts_params.map { Account.new(_1).tap(&:valid?) }
    ActiveRecord::Base.transaction do
      is_success = @accounts.none? { _1.errors.any? } and @accounts.all?(&:save!)
      raise ActiveRecord::RecordInvalid unless is_success
    end
  rescue ActiveRecord::RecordInvalid
    is_success = false
  rescue ActiveRecord::RecordNotUnique
    is_success = false
    flash.now[:alert] = "Account already exists."
  ensure
    if is_success
      redirect_to new_bulk_account_url, notice: "Accounts were successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def accounts_params
      params.require(:accounts).map { _1.permit(:name, :email) }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulk_accounts/groups_helper.rb
module BulkAccounts::GroupsHelper
end

app/helpers/bulk_accounts_helper.rb
module BulkAccountsHelper
end

app/views/bulk_accounts/_account.html.erb
<%= tag.div data: { controller: "element-removal" }, class: "relative block shadow rounded-md border border-gray-200 outline-none py-2 px-3 mb-5" do %>
  <div class="flex justify-end">
    <a hidden data-action="element-removal#remove" data-only-child-hidden-target="hiddenElement" class="absolute -top-4 -right-4 cursor-pointer">
      <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="flex justify-center items-center w-8 h-8 rounded-full bg-white border-2 border-gray-200 text-blue-600 text-4xl" viewBox="0 0 16 16">
        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
      </svg>
    </a>
  </div>
  <%= fields_for "accounts[]", account do |account_fields| %>
    <%= render "bulk_accounts/account_text_field", account: account, account_fields: account_fields, key: :name %>
    <%= render "bulk_accounts/account_text_field", account: account, account_fields: account_fields, key: :email %>
  <% end %>
<% end %>

app/views/bulk_accounts/_account_text_field.html.erb
<div class="my-5">
  <%= account_fields.label key %>
  <%= account_fields.text_field key, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <% if account.errors[key].any? %>
    <div class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <%= account.errors.full_messages_for(key).first %>
    </div>
  <% end%>
</div>

app/views/bulk_accounts/groups/create.turbo_stream.erb
<%= turbo_stream.append "accounts" do %>
  <%= render "bulk_accounts/account", account: Account.new %>
<% end %>

app/views/bulk_accounts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>

  <h1 class="font-bold text-4xl mb-10">New accounts</h1>

  <%= form_with(url: :bulk_accounts, data: { controller: "only-child-hidden" }) do |form| %>
    <div id="accounts" data-only-child-hidden-target="childList">
      <%= render partial: "account", collection: @accounts %>
    </div>
    <div class="relative flex justify-center -mt-10 mb-10">
      <%= link_to(bulk_accounts_group_path, data: { turbo_method: :post }, class: "flex justify-center items-center w-12 h-12 rounded-full bg-white border-2 border-gray-200 text-blue-600 text-4xl cursor-pointer") do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-9 h-9" viewBox="0 0 16 16">
          <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
      <% end %>
    </div>
    <div>
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BulkAccount</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>